name: Run GistScript (more race conditions)

on: 
  push:
  
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      
      - uses: actions/cache@v3
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Install Dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: cd $GITHUB_WORKSPACE && python -m pip install -r requirements.txt
      
      - name: Do some trolling
        run: cd $GITHUB_WORKSPACE && python main.py --oneoff
