name: Run GistScript (more race conditions)

on: 
  push:
  
  schedule:
    - cron: '*/5 * * * *'

jobs:
  trolling:
    name: Run GistScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Do some trolling
        run: cd $GITHUB_WORKSPACE && python main.py --oneoff
